spring:
  application:
    name: 'service-a'
  redis:
    host: localhost
    port: 6379
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
logging:
  level:
    org.springframework.cache: TRACE