spring:
  application:
    name: 'service-a'
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true